#!/bin/bash

echo "🚀 WaveSight Creator Monetization - Stripe Setup Guide"
echo "====================================================="
echo ""

echo "📋 STEP 1: Create Stripe Account"
echo "1. Go to https://dashboard.stripe.com/register"
echo "2. Create a new Stripe account or log in"
echo "3. Complete account verification"
echo ""

echo "🔑 STEP 2: Get API Keys"
echo "1. Go to https://dashboard.stripe.com/test/apikeys"
echo "2. Copy your 'Publishable key' (pk_test_...)"
echo "3. Reveal and copy your 'Secret key' (sk_test_...)"
echo "4. Add them to web/.env.local file"
echo ""

echo "💰 STEP 3: Create Products & Prices"
echo "1. Go to https://dashboard.stripe.com/test/products"
echo "2. Click 'Add product'"
echo ""
echo "CREATE PRODUCT: WaveSight Creator"
echo "- Name: WaveSight Creator Pro"
echo "- Description: AI-powered trend insights for content creators"
echo "- Pricing model: Recurring"
echo "- Price: \$49.00 USD"
echo "- Billing period: Monthly"
echo "- Copy the Price ID (price_...) to STRIPE_CREATOR_MONTHLY_PRICE_ID"
echo ""

echo "🪝 STEP 4: Set Up Webhooks"
echo "1. Go to https://dashboard.stripe.com/test/webhooks"
echo "2. Click 'Add endpoint'"
echo "3. Endpoint URL: http://localhost:3000/api/stripe/webhook"
echo "4. Select these events:"
echo "   - customer.subscription.created"
echo "   - customer.subscription.updated"
echo "   - customer.subscription.deleted"
echo "   - invoice.payment_succeeded"
echo "   - invoice.payment_failed"
echo "   - checkout.session.completed"
echo "5. Copy the 'Signing secret' (whsec_...) to STRIPE_WEBHOOK_SECRET"
echo ""

echo "📊 STEP 5: Update Environment Variables"
echo "Edit web/.env.local and replace these values:"
echo ""
echo "STRIPE_SECRET_KEY=sk_test_YOUR_SECRET_KEY_HERE"
echo "STRIPE_PUBLISHABLE_KEY=pk_test_YOUR_PUBLISHABLE_KEY_HERE"
echo "STRIPE_WEBHOOK_SECRET=whsec_YOUR_WEBHOOK_SECRET_HERE"
echo "STRIPE_CREATOR_MONTHLY_PRICE_ID=price_YOUR_PRICE_ID_HERE"
echo ""

echo "🧪 STEP 6: Test the Payment Flow"
echo "1. Restart your development server: npm run dev"
echo "2. Go to http://localhost:3000/creator"
echo "3. Click 'Start Free Trial'"
echo "4. Use Stripe test card: 4242 4242 4242 4242"
echo "5. Any future date for expiry, any 3-digit CVC"
echo ""

echo "💡 STEP 7: Go Live (When Ready)"
echo "1. Complete Stripe account verification"
echo "2. Switch to live API keys in production"
echo "3. Update webhook URL to production domain"
echo "4. Test with real payment methods"
echo ""

echo "✅ QUICK START CHECKLIST:"
echo "□ Created Stripe account"
echo "□ Got API keys"
echo "□ Created Creator Pro product (\$49/month)"
echo "□ Set up webhook endpoint"
echo "□ Updated .env.local file"
echo "□ Tested payment flow"
echo ""

echo "🎯 REVENUE TARGETS:"
echo "100 customers = \$4,900/month"
echo "1,000 customers = \$49,000/month" 
echo "10,000 customers = \$490,000/month"
echo ""

echo "🚀 Your creator dashboard is at: http://localhost:3000/creator/dashboard"
echo "💰 Your landing page is at: http://localhost:3000/creator"
echo ""
echo "Ready to make money! 💸"