import type {
  DailyReport,
  Signal,
  Trend,
  TrendSignal,
} from "@/types";

// ---------------------------------------------------------------------------
// Seeded sample data. This is the working dataset for the MVP — the app is fully
// usable with zero external credentials. When Supabase is configured the data
// layer (lib/data.ts) reads from the database instead; this same shape is what
// supabase/schema.sql + supabase/seed.sql produce.
// ---------------------------------------------------------------------------

const NOW = "2026-06-14T07:00:00.000Z";
const CREATED = "2026-06-08T07:00:00.000Z";

export const SEED_TRENDS: Trend[] = [
  {
    id: "trend-quiet-luxury-workspace",
    name: "Quiet Luxury Workspace",
    slug: "quiet-luxury-workspace",
    one_line_summary:
      "Minimal, expensive-looking desk setups engineered to make remote work feel calm, elegant, and high-status.",
    detailed_summary:
      "A maturing offshoot of the 'quiet luxury' aesthetic, now applied to the home office. Creators are restyling cluttered WFH corners into restrained, tonal, gallery-like workspaces — warm woods, matte ceramics, a single good lamp, hidden cables. The flex is no longer the gear count; it's the calm. The format rewards taste over budget, which is why 'quiet luxury on an IKEA budget' edits are outperforming pure haul content.",
    category: "Productivity / Home / Design",
    emotional_tone: "aspirational, calm, premium",
    audience: "young professionals, design TikTok, WFH creators",
    lifecycle_stage: "accelerating",
    virality_type: "aesthetic",
    wavescore: 87,
    momentum_score: 88,
    sentiment_score: 82,
    brand_safety_score: 91,
    saturation_score: 42,
    commercial_relevance_score: 85,
    participation_difficulty: "medium",
    risk_level: "low",
    why_spreading:
      "Return-to-office anxiety is pushing people to make home feel worth staying in. The aesthetic signals status without shouting, which performs well in a downturn where overt flexing reads as tone-deaf. It's also intensely shoppable — every frame is a soft product placement.",
    who_should_join:
      "Furniture and lighting brands, desk-accessory makers, productivity apps, premium coffee brands, and visually literate creators who can art-direct a frame.",
    who_should_avoid:
      "Chaotic meme brands and discount-led retailers — the whole point is restraint, so a 'BUY 3 GET 1' energy breaks the spell.",
    best_platforms: ["TikTok", "Instagram", "Pinterest", "YouTube"],
    creative_angles: [
      "Before/after a cluttered WFH corner becoming a calm tonal workspace",
      "'Quiet luxury on an IKEA budget' — taste over price",
      "One-object-at-a-time builds where each item is justified, not hauled",
    ],
    sample_hooks: [
      "Your desk is why you hate working from home.",
      "Three things that made my setup feel 10x more expensive.",
      "Quiet luxury, but for people with IKEA furniture.",
    ],
    created_at: CREATED,
    updated_at: NOW,
  },
  {
    id: "trend-soft-reset-sunday",
    name: "Soft Reset Sunday",
    slug: "soft-reset-sunday",
    one_line_summary:
      "Sunday routines focused on gentle resetting rather than intense optimization.",
    detailed_summary:
      "A direct reaction to '5am that-girl' optimization culture. Soft Reset Sunday reframes the weekly reset as low-pressure self-care — tidying a little, a slow skincare moment, clean sheets, tea, an early night — explicitly framed as 'enough' rather than a productivity sprint. The emotional payload (relief, permission to rest) is driving unusually high positive sentiment and saves.",
    category: "Wellness / Beauty / Lifestyle",
    emotional_tone: "wholesome, restorative, aspirational",
    audience: "women 22–35, wellness creators, skincare brands",
    lifecycle_stage: "emerging",
    virality_type: "format",
    wavescore: 84,
    momentum_score: 80,
    sentiment_score: 88,
    brand_safety_score: 94,
    saturation_score: 35,
    commercial_relevance_score: 78,
    participation_difficulty: "easy",
    risk_level: "low",
    why_spreading:
      "Audiences are fatigued by hyper-optimized 'that girl' content and are rewarding the opposite: permission to do less. The format is template-friendly (a soft checklist over calm b-roll) so it's easy to remix, and the wholesome tone makes it extremely brand-safe.",
    who_should_join:
      "Skincare, tea, bedding, candles, journals, and wellness apps. Creators with a calm, sincere voice will outperform high-energy ones here.",
    who_should_avoid:
      "Brands whose pitch is hustle, urgency, or extreme transformation — the tone clash will read as cynical.",
    best_platforms: ["TikTok", "Instagram", "YouTube"],
    creative_angles: [
      "A 'soft' checklist that intentionally leaves things undone",
      "Product woven into a calm routine, never as the hero",
      "'Reset for people who are tired of self-improvement' POV",
    ],
    sample_hooks: [
      "Sunday night is where your week actually starts.",
      "A reset routine for people who are tired of self-improvement.",
      "The softest way to get your life together.",
    ],
    created_at: CREATED,
    updated_at: NOW,
  },
  {
    id: "trend-main-character-errand-run",
    name: "Main Character Errand Run",
    slug: "main-character-errand-run",
    one_line_summary:
      "Turning ordinary errands into cinematic lifestyle montages.",
    detailed_summary:
      "An evolution of 'romanticize your life' content, now hyper-specific: the grocery run, the post office, the pharmacy — shot like the opening of an indie film, scored with a needle-drop sound. It's a sound-and-format trend as much as an aesthetic one, which makes it a strong vehicle for independent musicians looking for a sync moment and for local businesses that suddenly become 'sets.'",
    category: "Music / Fashion / Lifestyle",
    emotional_tone: "playful, cinematic, romantic",
    audience: "Gen Z, indie pop listeners, fashion creators",
    lifecycle_stage: "accelerating",
    virality_type: "format",
    wavescore: 81,
    momentum_score: 84,
    sentiment_score: 79,
    brand_safety_score: 85,
    saturation_score: 48,
    commercial_relevance_score: 80,
    participation_difficulty: "easy",
    risk_level: "low",
    why_spreading:
      "It's a cheap, high-emotion format anyone can shoot on a phone, and the music-led structure gives indie artists a built-in distribution hook. Saturation is climbing, so the window for an original sound or a fresh location angle is closing.",
    who_should_join:
      "Indie musicians (as the sound), fashion brands, cafes, local businesses, and city/neighborhood guides.",
    who_should_avoid:
      "Brands that can't tolerate a slightly ironic, unpolished tone — over-produced versions feel like ads and underperform.",
    best_platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    creative_angles: [
      "Score a mundane errand with an unreleased track for a sync moment",
      "'POV: the grocery run needed a soundtrack' template",
      "Local business as the cinematic 'set' of the montage",
    ],
    sample_hooks: [
      "Romanticize the boring errand.",
      "POV: the grocery run needed a soundtrack.",
      "Your walk to get coffee is the movie.",
    ],
    created_at: CREATED,
    updated_at: NOW,
  },
  {
    id: "trend-anti-haul-luxury",
    name: "Anti-Haul Luxury",
    slug: "anti-haul-luxury",
    one_line_summary:
      "Creators explaining which expensive items they are NOT buying, and why.",
    detailed_summary:
      "A skeptical, anti-waste counter-format to haul culture. Creators walk through luxury and viral-hype items they've decided against — calling out 'mostly marketing' products — while still affirming a love of quality. It signals taste and discernment rather than spending power, and it builds outsized trust, which converts well for durable, genuinely-good-quality brands.",
    category: "Fashion / Consumer Behavior",
    emotional_tone: "practical, skeptical, anti-waste",
    audience: "fashion-conscious millennials, sustainable shoppers",
    lifecycle_stage: "emerging",
    virality_type: "identity_signal",
    wavescore: 78,
    momentum_score: 72,
    sentiment_score: 73,
    brand_safety_score: 76,
    saturation_score: 30,
    commercial_relevance_score: 70,
    participation_difficulty: "medium",
    risk_level: "medium",
    why_spreading:
      "Cost-of-living pressure plus haul fatigue makes 'what I'm NOT buying' feel honest and high-status. It builds trust fast — but because it names-and-shames products, it carries comparative-claim and backlash risk.",
    who_should_join:
      "Durable goods, sustainable fashion, resale platforms, and finance/value creators who can credibly argue quality-over-hype.",
    who_should_avoid:
      "Fast fashion and impulse-buy brands — the format is structurally against them and will invite ratio in the comments.",
    best_platforms: ["TikTok", "YouTube", "Substack"],
    creative_angles: [
      "'Luxury items that are mostly marketing' explainer",
      "Cost-per-wear math defending the few things worth buying",
      "An anti-haul that still celebrates one beautiful, durable object",
    ],
    sample_hooks: [
      "Things I'm not buying even though everyone says I need them.",
      "Luxury items that are mostly marketing.",
      "The anti-haul for people who still love beautiful things.",
    ],
    created_at: CREATED,
    updated_at: NOW,
  },
  {
    id: "trend-cozy-competence",
    name: "Cozy Competence",
    slug: "cozy-competence",
    one_line_summary:
      "Rejecting hustle culture in favor of being organized, capable, and calm.",
    detailed_summary:
      "A productivity aesthetic that swaps grind-and-burnout for quiet capability — good systems, a tidy second brain, a warm desk, finishing on time and logging off. It positions calm competence as the new flex. Extremely brand-safe and low-saturation, it's an ideal vehicle for tools and stationery that promise control without anxiety.",
    category: "Productivity / Career",
    emotional_tone: "competent, warm, low-anxiety",
    audience: "young professionals, students, remote workers",
    lifecycle_stage: "emerging",
    virality_type: "identity_signal",
    wavescore: 80,
    momentum_score: 78,
    sentiment_score: 86,
    brand_safety_score: 90,
    saturation_score: 28,
    commercial_relevance_score: 76,
    participation_difficulty: "easy",
    risk_level: "low",
    why_spreading:
      "Burnout backlash is mainstream, and audiences are rewarding content that promises capability without the cortisol. Low saturation plus high sentiment means there's still room to define the category.",
    who_should_join:
      "Productivity tools, notebooks and stationery, premium coffee, and career creators who teach calm systems.",
    who_should_avoid:
      "Anything that sells via urgency, fear-of-missing-out, or 'grind harder' messaging.",
    best_platforms: ["TikTok", "Instagram", "YouTube", "LinkedIn"],
    creative_angles: [
      "'Calm competence is the new productivity aesthetic' manifesto",
      "A repeatable system demo (not a hustle routine)",
      "How to look like you have it together without burning out",
    ],
    sample_hooks: [
      "You don't need to hustle. You need a system.",
      "Calm competence is the new productivity aesthetic.",
      "How to look like you have your life together without burning out.",
    ],
    created_at: CREATED,
    updated_at: NOW,
  },
];

export const SEED_SIGNALS: Signal[] = [
  {
    id: "signal-qlw-1",
    source: "tiktok",
    url: "https://www.tiktok.com/@deskstudies/video/quiet-luxury-desk",
    title: "turning my chaotic wfh corner into a quiet luxury workspace",
    text: "no new desk, no big budget. just removed 80% of the stuff, added one warm lamp and a ceramic tray for cables. it feels expensive now and i actually want to work here.",
    creator_name: "@deskstudies",
    platform_engagement_json: { views: 1_240_000, likes: 218_000, saves: 41_000 },
    raw_metadata_json: { sound: "ambient-piano-loop", duration_s: 23 },
    detected_phrases: ["quiet luxury workspace", "it feels expensive now"],
    detected_entities: ["IKEA", "ceramic tray"],
    detected_emotions: ["calm", "aspiration", "satisfaction"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-qlw-2",
    source: "reddit",
    url: "https://www.reddit.com/r/workspaces/comments/quiet-luxury",
    title: "Why does everyone's desk suddenly look like a boutique hotel?",
    text: "Noticing a big shift away from RGB gamer battlestations toward minimal, tonal, 'calm' desks. Tons of upvotes for the understated builds now.",
    creator_name: "u/setupcurator",
    platform_engagement_json: { upvotes: 8400, comments: 612 },
    raw_metadata_json: { subreddit: "workspaces" },
    detected_phrases: ["boutique hotel desk", "calm desks"],
    detected_entities: ["RGB", "battlestation"],
    detected_emotions: ["curiosity", "aspiration"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-srs-1",
    source: "tiktok",
    url: "https://www.tiktok.com/@slowsundays/video/soft-reset",
    title: "soft reset sunday for people who are tired",
    text: "not a 5am routine. just clean sheets, a slow skincare moment, tea, and going to bed early. this is enough.",
    creator_name: "@slowsundays",
    platform_engagement_json: { views: 2_010_000, likes: 410_000, saves: 96_000 },
    raw_metadata_json: { sound: "lo-fi-rain", duration_s: 31 },
    detected_phrases: ["soft reset sunday", "this is enough"],
    detected_entities: ["skincare", "tea"],
    detected_emotions: ["relief", "comfort", "permission"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-srs-2",
    source: "instagram",
    url: "https://www.instagram.com/reel/soft-reset-sunday",
    title: "the anti-that-girl reset",
    text: "everyone's selling 5am cold plunges. here's a reset that doesn't make you hate yourself.",
    creator_name: "@gentleroutines",
    platform_engagement_json: { plays: 740_000, likes: 132_000, saves: 38_000 },
    raw_metadata_json: { format: "reel" },
    detected_phrases: ["anti that girl", "reset that doesn't make you hate yourself"],
    detected_entities: ["cold plunge", "5am"],
    detected_emotions: ["relief", "reassurance"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-mcer-1",
    source: "tiktok",
    url: "https://www.tiktok.com/@cinematicerrands/video/grocery-movie",
    title: "POV: the grocery run needed a soundtrack",
    text: "shot my normal saturday errands like an A24 trailer. used my friend's unreleased song. it's now stuck in everyone's head.",
    creator_name: "@cinematicerrands",
    platform_engagement_json: { views: 3_300_000, likes: 590_000, shares: 71_000 },
    raw_metadata_json: { sound: "unreleased-indie-pop", duration_s: 18 },
    detected_phrases: ["needed a soundtrack", "main character errand"],
    detected_entities: ["A24", "grocery run"],
    detected_emotions: ["playfulness", "romance", "delight"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-mcer-2",
    source: "youtube",
    url: "https://www.youtube.com/shorts/errand-montage",
    title: "romanticizing my errands (full vlog energy in 60s)",
    text: "the post office, the pharmacy, the coffee. all of it deserves a montage honestly.",
    creator_name: "Maya R.",
    platform_engagement_json: { views: 880_000, likes: 97_000 },
    raw_metadata_json: { format: "short" },
    detected_phrases: ["deserves a montage", "vlog energy"],
    detected_entities: ["post office", "pharmacy"],
    detected_emotions: ["romance", "warmth"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-ahl-1",
    source: "youtube",
    url: "https://www.youtube.com/watch?v=anti-haul-luxury",
    title: "Luxury items that are mostly marketing (an anti-haul)",
    text: "I love nice things but half of these viral 'investment' pieces are just logo tax. here's what I'm NOT buying and what I'd get instead.",
    creator_name: "The Considered Closet",
    platform_engagement_json: { views: 520_000, likes: 61_000, comments: 9_800 },
    raw_metadata_json: { duration_s: 720 },
    detected_phrases: ["mostly marketing", "logo tax", "what I'm not buying"],
    detected_entities: ["investment piece", "luxury"],
    detected_emotions: ["skepticism", "trust", "practicality"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-ahl-2",
    source: "reddit",
    url: "https://www.reddit.com/r/femalefashionadvice/comments/anti-haul",
    title: "The anti-haul is the only fashion content I trust now",
    text: "Sick of hauls. The creators telling me what to skip have way more credibility. Comments are split though — some say it's just negativity for clicks.",
    creator_name: "u/slowfashionfan",
    platform_engagement_json: { upvotes: 4100, comments: 880 },
    raw_metadata_json: { subreddit: "femalefashionadvice", sentiment_split: true },
    detected_phrases: ["only content I trust", "negativity for clicks"],
    detected_entities: ["haul", "anti-haul"],
    detected_emotions: ["trust", "skepticism", "irritation"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-cc-1",
    source: "tiktok",
    url: "https://www.tiktok.com/@calmsystems/video/cozy-competence",
    title: "calm competence is the new productivity aesthetic",
    text: "you don't need to hustle, you need a system. here's the boring setup that lets me log off at 5 and not think about work.",
    creator_name: "@calmsystems",
    platform_engagement_json: { views: 1_560_000, likes: 247_000, saves: 88_000 },
    raw_metadata_json: { sound: "soft-jazz", duration_s: 27 },
    detected_phrases: ["calm competence", "you need a system"],
    detected_entities: ["Notion", "second brain"],
    detected_emotions: ["reassurance", "competence", "calm"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
  {
    id: "signal-cc-2",
    source: "article",
    url: "https://example-culture-mag.com/cozy-competence-rise",
    title: "Hustle Is Out. 'Cozy Competence' Is the New Status Signal.",
    text: "A growing cohort of young workers are rejecting performative busyness in favor of quiet reliability — and turning it into an aesthetic.",
    creator_name: "Culture Desk",
    platform_engagement_json: { shares: 12_400 },
    raw_metadata_json: { outlet: "culture-mag" },
    detected_phrases: ["hustle is out", "quiet reliability"],
    detected_entities: ["status signal"],
    detected_emotions: ["calm", "validation"],
    submitted_by: null,
    created_at: CREATED,
    ingested_at: CREATED,
  },
];

export const SEED_TREND_SIGNALS: TrendSignal[] = [
  { id: "ts-1", trend_id: "trend-quiet-luxury-workspace", signal_id: "signal-qlw-1", relevance_score: 96, created_at: CREATED },
  { id: "ts-2", trend_id: "trend-quiet-luxury-workspace", signal_id: "signal-qlw-2", relevance_score: 88, created_at: CREATED },
  { id: "ts-3", trend_id: "trend-soft-reset-sunday", signal_id: "signal-srs-1", relevance_score: 97, created_at: CREATED },
  { id: "ts-4", trend_id: "trend-soft-reset-sunday", signal_id: "signal-srs-2", relevance_score: 90, created_at: CREATED },
  { id: "ts-5", trend_id: "trend-main-character-errand-run", signal_id: "signal-mcer-1", relevance_score: 98, created_at: CREATED },
  { id: "ts-6", trend_id: "trend-main-character-errand-run", signal_id: "signal-mcer-2", relevance_score: 85, created_at: CREATED },
  { id: "ts-7", trend_id: "trend-anti-haul-luxury", signal_id: "signal-ahl-1", relevance_score: 95, created_at: CREATED },
  { id: "ts-8", trend_id: "trend-anti-haul-luxury", signal_id: "signal-ahl-2", relevance_score: 87, created_at: CREATED },
  { id: "ts-9", trend_id: "trend-cozy-competence", signal_id: "signal-cc-1", relevance_score: 96, created_at: CREATED },
  { id: "ts-10", trend_id: "trend-cozy-competence", signal_id: "signal-cc-2", relevance_score: 89, created_at: CREATED },
];

export const SEED_DAILY_REPORT: DailyReport = {
  id: "report-2026-06-14",
  report_date: "2026-06-14",
  title: "WaveSight Daily — Calm Is the New Flex",
  summary:
    "Today's board is dominated by a single cultural undercurrent: audiences are rewarding restraint over excess. Quiet Luxury Workspace, Cozy Competence, and Soft Reset Sunday all monetize calm — strong sentiment, low-to-moderate saturation, and high brand safety. Main Character Errand Run is the fastest-moving format play (best for indie sound syncs) but is approaching saturation. Anti-Haul Luxury is the highest-trust, highest-risk pick.",
  top_trend_ids: [
    "trend-quiet-luxury-workspace",
    "trend-soft-reset-sunday",
    "trend-main-character-errand-run",
  ],
  generated_report: [
    "## The big picture",
    "Three of today's top five trends are explicitly *anti-hustle*. The cultural appetite has shifted from 'more' to 'enough' — and brands that can sell calm, taste, and control are positioned to win without looking like they're trying.",
    "",
    "### 1. Quiet Luxury Workspace — WaveScore 87 · accelerating",
    "The strongest all-round opportunity: high momentum, premium sentiment, and excellent brand safety. Best for furniture, lighting, desk-accessory, and premium coffee brands. Lead with taste, not price.",
    "",
    "### 2. Soft Reset Sunday — WaveScore 84 · emerging",
    "Highest sentiment on the board (88) and the most brand-safe (94). A natural fit for skincare, tea, bedding, and wellness apps. The window is wide open — saturation is still low.",
    "",
    "### 3. Main Character Errand Run — WaveScore 81 · accelerating",
    "The format moving fastest, and the best vehicle on the board for an indie musician chasing a sound sync. Saturation is climbing (48) — move now with an original sound or a fresh location.",
    "",
    "### Watchlist",
    "**Cozy Competence (80)** is the lowest-saturation pick and may overtake the leaders. **Anti-Haul Luxury (78)** earns the most trust but carries comparative-claim and backlash risk — handle with care.",
    "",
    "### How to act today",
    "If you have one move: ride Soft Reset Sunday or Cozy Competence while saturation is low. If you have budget and taste: own Quiet Luxury Workspace. If you have a song: Main Character Errand Run, today.",
  ].join("\n"),
  created_at: NOW,
};
