-- Add missing vote tracking columns to trend_submissions
ALTER TABLE trend_submissions 
ADD COLUMN IF NOT EXISTS heat_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS wave_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fire_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS declining_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS dead_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_votes INTEGER DEFAULT 0;